name: CI/CD Build

env:
  SHOULD_DEPLOY: >-
    ${{
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      (
        github.ref == 'refs/heads/main'||
        github.ref == 'refs/heads/miland/cucumber_debug'||
        github.ref == 'refs/heads/production'
      )
    }}
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package.json', 'package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run unit and integration tests
        run: npm run test:unit-integration-ci
      - name: Run end-to-end tests
        run: npm run test:e2e
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: test-results/
          retention-days: 7
          if-no-files-found: error
      - name: Report build to Ketryx
        uses: Ketryx/ketryx-github-action@v1
        if: fromJSON(env.SHOULD_DEPLOY) && (success() || failure())
        with:
          ketryx-url: https://ketryx-miland.eu.ngrok.io
          project: KXPRJ6504HQPM6W984T43VCD4GY5X8K
          api-key: KXTK_90NDVRSPTRJJGP5FKQ0MYRJJJNEB0HJP2SA8D8NQYJBPCP05EQB3EED27CPYG4XCKMM150QQHWGMK
          build-name: ci
          test-junit-path: test-results/jest-junit.xml
          test-cucumber-path: test-results/cucumber-report.json
